export const WORKSPACE_USE_VALUES = ['WORK', 'PERSONAL', 'SCHOOL'] as const;

export const WORKSPACE_MANAGEMENT_TYPE_VALUES = [
  'HR_RECRUITING',
  'CREATIVE_DESIGN',
  'PROFESSIONAL_SERVICES',
  'FINANCE_ACCOUNTING',
  'OPERATIONS',
  'SOFTWARE_DEVELOPMENT',
  'IT',
  'SALES_CRM',
  'PERSONAL_USE',
  'SUPPORT',
  'STARTUP',
  'PMO',
  'MARKETING',
  'OTHER',
] as const;
