export const DEFAULT_ACTIVITY_LIMIT = 25;
export const MAX_ACTIVITY_LIMIT = 100;

export const ACTIVITY_ENTITY_TYPES = [
  'workspace',
  'workspace_member',
  'workspace_invite',
  'project',
  'task_list',
  'status',
  'tag',
  'task',
  'comment',
  'attachment',
  'time_entry',
  'user',
] as const;

export const ACTIVITY_CATEGORIES = [
  'workspace',
  'member',
  'invite',
  'project',
  'list',
  'status',
  'tag',
  'task_creation',
  'name',
  'description',
  'priority',
  'start_date',
  'due_date',
  'completion',
  'assignee',
  'tags',
  'attachments',
  'comments',
  'time_tracked',
  'list_moved',
  'subtask',
  'archived_deleted',
  'reorder',
] as const;

export type ActivityEntityType = (typeof ACTIVITY_ENTITY_TYPES)[number];
export type ActivityCategory = (typeof ACTIVITY_CATEGORIES)[number];

export const FIELD_CATEGORY_MAP: Record<string, ActivityCategory> = {
  title: 'name',
  name: 'name',
  description: 'description',
  priority: 'priority',
  startDate: 'start_date',
  dueDate: 'due_date',
  status: 'status',
  statusId: 'status',
  listId: 'list_moved',
  isCompleted: 'completion',
  completedAt: 'completion',
  role: 'member',
};

export const ACTION_CATEGORY_MAP: Record<string, ActivityCategory> = {
  task_created: 'task_creation',
  subtask_created: 'subtask',
  completed: 'completion',
  uncompleted: 'completion',
  assignee_added: 'assignee',
  assignees_added: 'assignee',
  assignee_removed: 'assignee',
  assigned: 'assignee',
  unassigned: 'assignee',
  tag_added: 'tags',
  tag_removed: 'tags',
  file_uploaded: 'attachments',
  file_deleted: 'attachments',
  attachment_added: 'attachments',
  attachment_deleted: 'attachments',
  comment_added: 'comments',
  comment_created: 'comments',
  comment_updated: 'comments',
  comment_deleted: 'comments',
  manual_logged: 'time_tracked',
  timer_started: 'time_tracked',
  timer_stopped: 'time_tracked',
  time_entry_created: 'time_tracked',
  time_entry_updated: 'time_tracked',
  time_entry_deleted: 'time_tracked',
  moved: 'list_moved',
  reordered: 'reorder',
  archived: 'archived_deleted',
  restored: 'archived_deleted',
  deleted: 'archived_deleted',
  deleted_by_owner: 'member',
  member_added: 'member',
  member_removed: 'member',
  member_role_changed: 'member',
  invite_sent: 'invite',
  invite_accepted: 'invite',
  invite_revoked: 'invite',
};
